config/routes.rb
Rails.application.routes.draw do
  get 'report/customers'

  get 'custmgmt/custprod'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'community/reports'

  resources :promotions
  resources :reviews
  resources :subscriptions
  resources :order_items
  resources :orders
  resources :categories
  resources :reorders
  resources :suppliers
  resources :products
  resources :customers
  
  get 'home/index'

  get 'home/about'

  get 'home/contact'
  
  get 'home/catalog'
  
  get 'home/product'

  get 'home/index'

  get 'home/about'

  get 'home/contact'
  
  get 'home/privacy'
  
  get 'home/help'
  
  get 'home/search'  
  post 'home/search'
  post 'home/buy'
  post "home/updatecart"
  post "home/checkout"
  get "cart" => "home#cart", :as => "cart"
  
  get "login" => "sessions#new", :as => "login"
  delete 'logout' => "sessions#destroy", :as => "logout"
  resources :sessions

  
  
  root "home#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :categoryname, presence: true
	has_many :product, dependent:  :destroy
	has_many :subscription, dependent:  :destroy
end

app/models/customer.rb
class Customer < ActiveRecord::Base

 validates :firstname, presence: true
 validates :lastname, presence: true
 validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
 
 validates :username, :presence => true, :uniqueness => true

 has_secure_password

 
 def custname
    firstname + " " + lastname
 end

  # One customer may have many orders
  # Delete dependent orders when delete customer

   has_many :order, dependent:  :destroy
   has_many :review, dependent:  :destroy
   has_many :subscription, dependent:  :destroy

end

app/models/order.rb
class Order < ActiveRecord::Base

  # Each order belongs to only 1 customer
  belongs_to :customer

  # Each order may have one or more order_items
  has_many :order_item, dependent: :destroy
  
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
	
   # Each order item belongs to a specific product
   belongs_to :product 
   
   # Each order item belongs to a specific order
   belongs_to :order
   
end

app/models/product.rb
class Product < ActiveRecord::Base

	validates :productname, presence: true
	validates :productname, uniqueness: true
	validates :status, inclusion: { in: ["Active", "Inactive"] }
	
	
	# A product may have one or more Order Items
  has_many :order_item, dependent: :destroy
  belongs_to :category
  belongs_to :supplier
  has_many :reorder, dependent:  :destroy
  has_many :review, dependent:  :destroy

end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
end

app/models/reorder.rb
class Reorder < ActiveRecord::Base
	belongs_to :supplier
    belongs_to :product
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :customer
	belongs_to :product
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
belongs_to :category
belongs_to :customer
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
	has_many :reorder, dependent:  :destroy
	has_many :product, dependent: :destroy
end

app/models/us_state.rb
class UsState < ActiveRecord::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
skip_before_filter :authorize

  def index
      @timenow = Time.now
	  @promos = Promotion.where("startdate <= ? AND enddate >= ?",  Date.today, Date.today)
	  
	  @prod = Product.where('homepage = ?', true)

  end

  def cart
  end
  
  def about
  end

  def contact
  end

  def privacy
  end 

  def catalog
	@products = Product.all
  end 

  def buy
  
    # Get the specific product selected to be purchased and the quantity.
	# Converting the value to integer using the to_i method
	@prodid = params[:prodid].to_i;
	@qty = params[:qty].to_i;
	
	# Set session cart arrays to nil. 
	session[:cart_prod] << @prodid
	session[:cart_qty] << @qty

	# Redirect to display cart (shopping cart)
	redirect_to cart_url
 
  end 
 

	 def updatecart
		# Get the specific item that needs to be removed
		cartid = params[:cartid].to_i;
	  
		 # Remove the specific element that is desired to be removed from the array.
		session[:cart_prod].delete_at(cartid)
		session[:cart_qty].delete_at(cartid)
	  
		# Redirect to display cart (shopping cart)
		redirect_to cart_url
	 end


	def checkout
		cartlen = session[:cart_prod].length
		i=0
		if cartlen > 0
		 # Save new record in Order table
		 # Customer ID, Sale Date and Sale Notes
		 orderid = Order.create(customer_id: session[:user_id], saledate: Date.today, salenotes: session[:cart_prod].to_s)

		 # For each item in the shopping cart save the record in the in OrderItem table
		while i < cartlen
			OrderItem.create(order_id: orderid.id, product_id: session[:cart_prod][i].to_i, saleprice: Product.find(session[:cart_prod][i].to_i).saleprice, prodqty: session[:cart_qty][i])
			i = i + 1
		end 
		# Set session cart arrays to nil. 
		  session[:cart_prod] = Array.new
		  session[:cart_qty] = Array.new
		end
	end

 
  def search
    @results=0
	if !params[:searchinput].empty?
		@results=1
		@searchinput = params[:searchinput]
		@searchcriteria="%#{params[:searchinput]}%"	
		@productlist = Product.where("productname like ? OR description like ?",@searchcriteria, @searchcriteria)
		@reviewlist = Review.where("comments like ?",@searchcriteria)
	end 

  end
  
  
end

app/helpers/community_helper.rb
module CommunityHelper
end

app/helpers/custmgmt_helper.rb
module CustmgmtHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reorders_helper.rb
module ReordersHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/about.html.erb
 <h1>About Us</h1>
 <%= link_to "Home", home_index_path %> <br/>
 <%= link_to "About Us", home_about_path %> <br/>
 <%= link_to "Contact us", home_contact_path %> <br/>

app/views/home/cart.html.erb
<h1>Shopping Cart</h1>
<% i=0 %>
<% totqty=0 %>
<% totprice=0 %>
<% cartlen = session[:cart_prod].length %>

<% if cartlen >0 %>
	<table border=1>
		<tr>
			<th> Product Image</th>
			<th> Product Name </th>
			<th> Sale Price </th>
			<th> Qty Selected </th>
			
		</tr>
		
	<% while i < cartlen %>
		<tr>
		 	
		<td> <%= link_to (image_tag( Product.find(session[:cart_prod][i].to_i).productimage,size:"100x100")) %> </td>
		<td> <%= Product.find(session[:cart_prod][i].to_i).productname %> </td>
			<td align='right'> <%= number_to_currency(Product.find(session[:cart_prod][i].to_i).saleprice) %> </td>
			<td align='center'> <%= session[:cart_qty][i] %> </td>
			<td> 
				<%= form_tag :controller => 'home', :action => 'updatecart' do %>
					<%= hidden_field_tag 'cartid', "#{i}" %>
					<%= submit_tag 'Remove' %>
			    <% end %>
			</td>
		</tr>
		<% totqty = totqty + session[:cart_qty][i].to_i %>
		<% totprice = totprice + (Product.find(session[:cart_prod][i].to_i).saleprice * session[:cart_qty][i].to_i) %>
		<% i = i + 1 %>
	<% end %>
	
		<tr bgcolor='yellow'>
			<td> <b> Total </b> </td>
			<td align='right'> <b> <%= number_to_currency(totprice) %> </b> </td>
			<td align='center'> <b> <%= totqty %> </b> </td>
		</tr>
	</table>
	
	<%= form_tag :controller => 'home', :action => 'checkout' do %>
		<%= submit_tag 'Checkout' %>
	<% end %>
				
<% else %>
	<p> There are no items in the cart. </p>

<% end %>

app/views/home/catalog.html.erb
<h1>Our Catalog</h1>

<% @products.each do |p| %>
	<product>
		<table width='100%'>
		<tr><td align='center'><b><%= link_to p.productname,  product_path(p.id) %> </b></td></tr>
		<tr><td><center><%= link_to (image_tag p.productimage, size:"100x100"), product_path(p.id) %> <%= p.description %>  </center></td></tr>
		
		<tr><td align='center'>
			<%= form_tag :controller => 'home', :action => 'buy' do %>
					<b>Price:</b> <%= number_to_currency(p.saleprice) %>
					<%= hidden_field_tag 'prodid', "#{p.id}" %> </br>
					<%= select_tag "qty", "<option>1</option> <option>2</option> <option>3</option> <option>4</option> <option>5</option>".html_safe %>
					<%= submit_tag 'Add To Cart', :class => 'button1' %>
			<% end %>
		</td></tr>
		</table>
	</product>
<% end %> 

app/views/home/checkout.html.erb
<h1>Checkout Completed</h1>

<p> Thank you for your order! </p>

<p> We will provide you update via email on the progress of shipment. </p>

app/views/home/contact.html.erb
 <h1>Contact Us</h1>
 <%= link_to (image_tag 'Help.png'), home_contact_path%>
 
 
<b>Contact Us </br>

Email :admin@test.com<br/>
phone :630-134-4545</b>

 

    

app/views/home/help.html.erb
<h1> Help </h1>

 <%= link_to (image_tag 'Help2.png'), home_help_path%>
 

app/views/home/index.html.erb
<h1>Welcome to Patel Tech </h1>

<table> <tr>
	<td width='80%' align='left'>

		<% @prod.each do |p| %>
			<product>
				<table width='100%'>
				<tr><td align='center'><b><%= link_to p.productname,  product_path(p.id) %> </b></td></tr>
				<tr><td><center><%= link_to (image_tag p.productimage, size:"100x100"), product_path(p.id) %> <%= p.description %>  </center></td></tr>
				
				<tr><td align='center'>
					<%= form_tag :controller => 'home', :action => 'buy' do %>
							<b>Price:</b> <%= number_to_currency(p.saleprice) %>
							<%= hidden_field_tag 'prodid', "#{p.id}" %> </br>
							<%= select_tag "qty", "<option>1</option> <option>2</option> <option>3</option> <option>4</option> <option>5</option>".html_safe %>
							<%= submit_tag 'Add To Cart', :class => 'button1' %>
					<% end %>
				</td></tr>
				</table>
			</product>
		<% end %> 


	
	</td>
	
	<td width='20%' alight='right'>
	     <% @promos.each do |p| %>
				<p><b><%= p.title %></b> </br>
				<%= p.description %> </br>
				<%= image_tag p.imagepath, size:"50x50" %></br></p> </br>
				<hr>
		 <% end %>
	
	</td>
	
	 
</tr>

<td>
 </table>
	

app/views/home/privacy.html.erb
<h1> Privacy policies</h1>


 This Privacy Statement informs you of our privacy practices and of the choices you can make about the way information about you,<br> including from your online activity is collected and how that information is used by Patel TECH. <br> 
This statement is readily available on our Patel TECH.com home page and at the bottom of every Patel Tech web page. <br>
Please use the links below to access translations of this statement and any applicable country specific or service specific supplements to the statement.

app/views/home/report.html.erb
<h1>Report </h1>

<%= link_to "Report", report_index_path %> <br/>

app/views/home/search.html.erb
<h1>Search Results</h1>

<%= form_tag :action => 'search' do %>
	<p>What product are you looking for?: 
	<%= text_field_tag 'searchinput', @searchinput %> </p>
	<hr/>
	<% if @results>0 %>
		<% if @productlist.length >0 %>
			<h2> Here are the product search results:</h2>
			<p>
			<table>
			<tr>
				<th>Product Name</th>
				<th>Image</th>
				<th>Description</th>
			</tr>
			<% @productlist.each do |p| %>
				<tr>
				<td><%= link_to p.productname, product_path(p.id) %></td>
				<td><%= p.productimage %></td>
				<td><%= p.description %></td>
				</tr>
			<% end %>
			</table>

		<% else%>
			<p>There were no products with your search criteria.</p>
		<% end %>

		<% if @reviewlist.length >0 %>
			<h2> Here are the review search results:</h2>
			<p>
			<table>
			<tr>
				<th>Product </th>
				<th>Username</th>
				<th>Comments</th>
			</tr>
			<% @reviewlist.each do |r| %>
				<td><%= link_to Product.find(r.product_id).productname, product_path(r.product_id) %></td>
				<td><%= Customer.find(r.customer_id).username %></td>
				<td><%= r.comments %></td>
				</tr>
			<% end %>
			</table>

		<% else%>
			<p>There were no reviews with your search criteria.</p>
		<% end %>
		
		
		
	<% end %>

	<%= submit_tag 'Search' %>
<% end %>