config/routes.rb
Rails.application.routes.draw do
  get 'report/customers'

  get 'custmgmt/custprod'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'community/reports'

  resources :promotions
  resources :reviews
  resources :subscriptions
  resources :order_items
  resources :orders
  resources :categories
  resources :reorders
  resources :suppliers
  resources :products
  resources :customers
  
  get 'home/index'

  get 'home/about'

  get 'home/contact'
  
  get 'home/catalog'
  
  get 'home/product'

  get 'home/index'

  get 'home/about'

  get 'home/contact'
  
  get 'home/privacy'
  
  get 'home/help'
  
  get 'home/search'  
  post 'home/search'
  post 'home/buy'
  post "home/updatecart"
  post "home/checkout"
  get "cart" => "home#cart", :as => "cart"
  
  get "login" => "sessions#new", :as => "login"
  delete 'logout' => "sessions#destroy", :as => "logout"
  resources :sessions

  
  
  root "home#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :categoryname, presence: true
	has_many :product, dependent:  :destroy
	has_many :subscription, dependent:  :destroy
end

app/models/customer.rb
class Customer < ActiveRecord::Base

 validates :firstname, presence: true
 validates :lastname, presence: true
 validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
 
 validates :username, :presence => true, :uniqueness => true

 has_secure_password

 
 def custname
    firstname + " " + lastname
 end

  # One customer may have many orders
  # Delete dependent orders when delete customer

   has_many :order, dependent:  :destroy
   has_many :review, dependent:  :destroy
   has_many :subscription, dependent:  :destroy

end

app/models/order.rb
class Order < ActiveRecord::Base

  # Each order belongs to only 1 customer
  belongs_to :customer

  # Each order may have one or more order_items
  has_many :order_item, dependent: :destroy
  
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
	
   # Each order item belongs to a specific product
   belongs_to :product 
   
   # Each order item belongs to a specific order
   belongs_to :order
   
end

app/models/product.rb
class Product < ActiveRecord::Base

	validates :productname, presence: true
	validates :productname, uniqueness: true
	validates :status, inclusion: { in: ["Active", "Inactive"] }
	
	
	# A product may have one or more Order Items
  has_many :order_item, dependent: :destroy
  belongs_to :category
  belongs_to :supplier
  has_many :reorder, dependent:  :destroy
  has_many :review, dependent:  :destroy

end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
end

app/models/reorder.rb
class Reorder < ActiveRecord::Base
	belongs_to :supplier
    belongs_to :product
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :customer
	belongs_to :product
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
belongs_to :category
belongs_to :customer
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
	has_many :reorder, dependent:  :destroy
	has_many :product, dependent: :destroy
end

app/models/us_state.rb
class UsState < ActiveRecord::Base
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:customer_id, :category_id, :subscribedate, :unsubscribedate)
    end
end

app/helpers/community_helper.rb
module CommunityHelper
end

app/helpers/custmgmt_helper.rb
module CustmgmtHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reorders_helper.rb
module ReordersHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.number_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :subscribedate %><br>
    <%= f.date_select :subscribedate %>
  </div>
  <div class="field">
    <%= f.label :unsubscribedate %><br>
    <%= f.date_select :unsubscribedate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Category</th>
      <th>Subscribedate</th>
      <th>Unsubscribedate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.customer_id %></td>
        <td><%= subscription.category_id %></td>
        <td><%= subscription.subscribedate %></td>
        <td><%= subscription.unsubscribedate %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New Subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @subscription.customer_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @subscription.category_id %>
</p>

<p>
  <strong>Subscribedate:</strong>
  <%= @subscription.subscribedate %>
</p>

<p>
  <strong>Unsubscribedate:</strong>
  <%= @subscription.unsubscribedate %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>