config/routes.rb
Rails.application.routes.draw do
  get 'report/customers'

  get 'custmgmt/custprod'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'community/reports'

  resources :promotions
  resources :reviews
  resources :subscriptions
  resources :order_items
  resources :orders
  resources :categories
  resources :reorders
  resources :suppliers
  resources :products
  resources :customers
  
  get 'home/index'

  get 'home/about'

  get 'home/contact'
  
  get 'home/catalog'
  
  get 'home/product'

  get 'home/index'

  get 'home/about'

  get 'home/contact'
  
  get 'home/privacy'
  
  get 'home/help'
  
  get 'home/search'  
  post 'home/search'
  post 'home/buy'
  post "home/updatecart"
  post "home/checkout"
  get "cart" => "home#cart", :as => "cart"
  
  get "login" => "sessions#new", :as => "login"
  delete 'logout' => "sessions#destroy", :as => "logout"
  resources :sessions

  
  
  root "home#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :categoryname, presence: true
	has_many :product, dependent:  :destroy
	has_many :subscription, dependent:  :destroy
end

app/models/customer.rb
class Customer < ActiveRecord::Base

 validates :firstname, presence: true
 validates :lastname, presence: true
 validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
 
 validates :username, :presence => true, :uniqueness => true

 has_secure_password

 
 def custname
    firstname + " " + lastname
 end

  # One customer may have many orders
  # Delete dependent orders when delete customer

   has_many :order, dependent:  :destroy
   has_many :review, dependent:  :destroy
   has_many :subscription, dependent:  :destroy

end

app/models/order.rb
class Order < ActiveRecord::Base

  # Each order belongs to only 1 customer
  belongs_to :customer

  # Each order may have one or more order_items
  has_many :order_item, dependent: :destroy
  
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
	
   # Each order item belongs to a specific product
   belongs_to :product 
   
   # Each order item belongs to a specific order
   belongs_to :order
   
end

app/models/product.rb
class Product < ActiveRecord::Base

	validates :productname, presence: true
	validates :productname, uniqueness: true
	validates :status, inclusion: { in: ["Active", "Inactive"] }
	
	
	# A product may have one or more Order Items
  has_many :order_item, dependent: :destroy
  belongs_to :category
  belongs_to :supplier
  has_many :reorder, dependent:  :destroy
  has_many :review, dependent:  :destroy

end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
end

app/models/reorder.rb
class Reorder < ActiveRecord::Base
	belongs_to :supplier
    belongs_to :product
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :customer
	belongs_to :product
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
belongs_to :category
belongs_to :customer
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
	has_many :reorder, dependent:  :destroy
	has_many :product, dependent: :destroy
end

app/models/us_state.rb
class UsState < ActiveRecord::Base
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
	@review.customer_id = params[:customer_id]
	@review.product_id = params[:product_id]
	@review.reviewdate = Time.now
	@review.status = "NeedReview"
	@prod_id = @review.product_id
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:customer_id, :product_id, :reviewdate, :comments, :rating, :status)
    end
end

app/helpers/community_helper.rb
module CommunityHelper
end

app/helpers/custmgmt_helper.rb
module CustmgmtHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reorders_helper.rb
module ReordersHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :customer_id %>
  </div>

  <div class="field">
    <%= f.hidden_field :product_id %>
	<%= Product.find(@prod_id).productname %>
</div>

  
  <div class="field">
    <%= f.hidden_field :reviewdate %>
  </div>

  <div class="field">
    <%= f.label :comments %>
    <%= f.text_area :comments %>
  </div>

  <div class="field">
    <%= f.label :rating %>
    <%= f.number_field :rating %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Product</th>
      <th>Reviewdate</th>
      <th>Comments</th>
      <th>Rating</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.customer_id %></td>
        <td><%= review.product_id %></td>
        <td><%= review.reviewdate %></td>
        <td><%= review.comments %></td>
        <td><%= review.rating %></td>
        <td><%= review.status %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @review.customer_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @review.product_id %>
</p>

<p>
  <strong>Reviewdate:</strong>
  <%= @review.reviewdate %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @review.comments %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Status:</strong>
  <%= @review.status %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', custmgmt_custprod_path %>